version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"  # S'il y a un Dockerfile Ã  la racine du repo
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "janus-php/"  # Pour le Dockerfile de ton infra
    schedule:
      interval: "daily"
